#include "PluginEditor.h"
#include "ReferenceAnalyzer.h"

namespace {
class VoiceLookAndFeel final : public juce::LookAndFeel_V4 {
public:
    VoiceLookAndFeel(){setColour(juce::Slider::rotarySliderFillColourId,juce::Colour(0xff00d9ff));setColour(juce::Slider::rotarySliderOutlineColourId,juce::Colour(0xff243c60));setColour(juce::Slider::thumbColourId,juce::Colours::white);setColour(juce::ComboBox::backgroundColourId,juce::Colour(0xff0b1527));setColour(juce::ComboBox::outlineColourId,juce::Colour(0xff168eb3));setColour(juce::TextButton::buttonColourId,juce::Colour(0xff0d4662));setColour(juce::TextButton::buttonOnColourId,juce::Colour(0xff7b36d4));}
    void drawRotarySlider(juce::Graphics&g,int x,int y,int w,int h,float pos,float start,float end,juce::Slider&)override{auto r=juce::Rectangle<float>((float)x,(float)y,(float)w,(float)h).reduced(8);auto radius=juce::jmin(r.getWidth(),r.getHeight())*.5f;auto c=r.getCentre();g.setColour(juce::Colour(0xff060a12));g.fillEllipse(r);g.setColour(juce::Colour(0xff243c60));g.drawEllipse(r,3);juce::Path arc;arc.addCentredArc(c.x,c.y,radius-2,radius-2,0,start,start+pos*(end-start),true);g.setColour(juce::Colour(0xff00d9ff));g.strokePath(arc,juce::PathStrokeType(4,juce::PathStrokeType::curved,juce::PathStrokeType::rounded));auto angle=start+pos*(end-start);juce::Path p;p.startNewSubPath(c);p.lineTo(c.x+std::sin(angle)*(radius-13),c.y-std::cos(angle)*(radius-13));g.setColour(juce::Colours::white);g.strokePath(p,juce::PathStrokeType(2.4f));}
};
VoiceLookAndFeel globalLook;
}

UCGVoiceWonderEditor::UCGVoiceWonderEditor(UCGVoiceWonderProcessor&p):AudioProcessorEditor(&p),processor(p){setLookAndFeel(&globalLook);setResizable(true,true);setResizeLimits(900,620,1500,1000);setSize(1180,760);title.setText("UCG  VOICE  WONDER  PRO",juce::dontSendNotification);title.setJustificationType(juce::Justification::centred);title.setFont(juce::Font(30,juce::Font::bold));subtitle.setText("TUNE • FORMANT • MATCH • VOCODER • VOICE→MIDI",juce::dontSendNotification);subtitle.setJustificationType(juce::Justification::centred);subtitle.setColour(juce::Label::textColourId,juce::Colour(0xff6deaff));status.setText("Carga una voz de tu librería para crear MATCH",juce::dontSendNotification);status.setColour(juce::Label::textColourId,juce::Colour(0xffa9b9cf));pitchReadout.setJustificationType(juce::Justification::centred);pitchReadout.setColour(juce::Label::textColourId,juce::Colour(0xff7cffb2));for(auto*l:{&title,&subtitle,&status,&pitchReadout})addAndMakeVisible(*l);
    const std::pair<const char*,const char*> specs[]={{"mix","MIX"},{"input","INPUT"},{"gate","GATE"},{"tune","TUNE AMOUNT"},{"tunespeed","TUNE SPEED"},{"pitch","PITCH"},{"formant","FORMANT"},{"warmth","WARMTH"},{"presence","PRESENCE"},{"air","AIR"},{"deess","DE-ESSER"},{"compress","COMPRESS"},{"drive","DRIVE"},{"radio","RADIO"},{"vocoder","VOCODER"},{"doubler","DOUBLER"},{"width","WIDTH"},{"delay","DELAY"},{"delaytime","DELAY TIME"},{"delayfeedback","FEEDBACK"},{"reverb","REVERB"},{"output","OUTPUT"}};for(const auto&s:specs)addKnob(s.first,s.second);
    presetLabel.setText("FACTORY PRESET",juce::dontSendNotification);keyLabel.setText("KEY",juce::dontSendNotification);scaleLabel.setText("SCALE",juce::dontSendNotification);for(auto*l:{&presetLabel,&keyLabel,&scaleLabel}){l->setColour(juce::Label::textColourId,juce::Colour(0xff8ea7c7));addAndMakeVisible(*l);}presetBox.addItemList(processor.getPresetNames(),1);presetBox.setSelectedId(processor.getCurrentProgram()+1,juce::dontSendNotification);presetBox.onChange=[this]{if(presetBox.getSelectedId()>0)processor.applyPreset(presetBox.getSelectedId()-1);};keyBox.addItemList({"C","C#","D","D#","E","F","F#","G","G#","A","A#","B"},1);scaleBox.addItemList({"CHROMATIC","MAJOR","MINOR"},1);for(auto*c:{&presetBox,&keyBox,&scaleBox})addAndMakeVisible(*c);keyAttachment=std::make_unique<ComboAttachment>(processor.apvts,"key",keyBox);scaleAttachment=std::make_unique<ComboAttachment>(processor.apvts,"scale",scaleBox);
    for(auto*b:{&analyseButton,&saveButton,&loadButton})addAndMakeVisible(*b);analyseButton.onClick=[this]{chooseReference();};saveButton.onClick=[this]{savePreset();};loadButton.onClick=[this]{loadPreset();};addAndMakeVisible(midiButton);midiAttachment=std::make_unique<ButtonAttachment>(processor.apvts,"midi",midiButton);startTimerHz(12);}

UCGVoiceWonderEditor::~UCGVoiceWonderEditor(){setLookAndFeel(nullptr);}
void UCGVoiceWonderEditor::addKnob(const juce::String&id,const juce::String&name){auto k=std::make_unique<Knob>();k->slider.setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);k->slider.setTextBoxStyle(juce::Slider::TextBoxBelow,false,86,20);k->label.setText(name,juce::dontSendNotification);k->label.setJustificationType(juce::Justification::centred);k->label.setColour(juce::Label::textColourId,juce::Colour(0xffd9e8ff));addAndMakeVisible(k->slider);addAndMakeVisible(k->label);k->attachment=std::make_unique<SliderAttachment>(processor.apvts,id,k->slider);knobs.push_back(std::move(k));}

void UCGVoiceWonderEditor::paint(juce::Graphics&g){g.fillAll(juce::Colour(0xff050912));auto area=getLocalBounds().toFloat().reduced(12);juce::ColourGradient grad(juce::Colour(0xff14243d),area.getTopLeft(),juce::Colour(0xff08111f),area.getBottomRight(),false);g.setGradientFill(grad);g.fillRoundedRectangle(area,18);g.setColour(juce::Colour(0xff00bfe8));g.drawRoundedRectangle(area,18,2);g.setColour(juce::Colour(0x353773ff));g.fillRoundedRectangle(juce::Rectangle<float>(24,112,(float)getWidth()-48,(float)getHeight()-215),14);g.setColour(juce::Colour(0xff214166));g.drawRoundedRectangle(juce::Rectangle<float>(24,112,(float)getWidth()-48,(float)getHeight()-215),14,1);}
void UCGVoiceWonderEditor::resized(){auto r=getLocalBounds().reduced(26);title.setBounds(r.removeFromTop(38));subtitle.setBounds(r.removeFromTop(24));auto top=r.removeFromTop(52);presetLabel.setBounds(top.removeFromLeft(112));presetBox.setBounds(top.removeFromLeft(250).reduced(2,8));keyLabel.setBounds(top.removeFromLeft(42));keyBox.setBounds(top.removeFromLeft(78).reduced(2,8));scaleLabel.setBounds(top.removeFromLeft(52));scaleBox.setBounds(top.removeFromLeft(120).reduced(2,8));pitchReadout.setBounds(top.removeFromRight(150));auto bottom=r.removeFromBottom(76);analyseButton.setBounds(bottom.removeFromLeft(205).reduced(4,18));saveButton.setBounds(bottom.removeFromLeft(130).reduced(4,18));loadButton.setBounds(bottom.removeFromLeft(130).reduced(4,18));midiButton.setBounds(bottom.removeFromRight(150).reduced(4,18));status.setBounds(bottom.reduced(8,12));auto grid=r.reduced(8,10);const int cols=6,rows=4;const int cw=grid.getWidth()/cols,ch=grid.getHeight()/rows;for(size_t i=0;i<knobs.size();i++){int row=(int)i/cols,col=(int)i%cols;auto cell=juce::Rectangle<int>(grid.getX()+col*cw,grid.getY()+row*ch,cw,ch);knobs[i]->label.setBounds(cell.removeFromTop(20));knobs[i]->slider.setBounds(cell.reduced(8,0));}}

void UCGVoiceWonderEditor::chooseReference(){fileChooser=std::make_unique<juce::FileChooser>("Selecciona una voz de referencia",juce::File{},"*.wav;*.mp3;*.flac;*.aif;*.aiff;*.ogg");auto safe=juce::Component::SafePointer<UCGVoiceWonderEditor>(this);fileChooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[safe](const juce::FileChooser&fc){if(safe==nullptr)return;auto file=fc.getResult();if(!file.existsAsFile())return;safe->status.setText("Analizando "+file.getFileName()+"...",juce::dontSendNotification);juce::Thread::launch([safe,file]{auto profile=ReferenceAnalyzer::analyse(file);juce::MessageManager::callAsync([safe,profile]{if(safe==nullptr)return;if(profile.valid){safe->processor.applyReferenceProfile(profile);safe->presetBox.setText("MATCH: "+profile.name,juce::dontSendNotification);}safe->status.setText(profile.summary(),juce::dontSendNotification);});});});}
void UCGVoiceWonderEditor::savePreset(){fileChooser=std::make_unique<juce::FileChooser>("Guardar preset",juce::File::getSpecialLocation(juce::File::userDocumentsDirectory).getChildFile("UCG-Voice-Wonder-Preset.ucgvw"),"*.ucgvw");auto safe=juce::Component::SafePointer<UCGVoiceWonderEditor>(this);fileChooser->launchAsync(juce::FileBrowserComponent::saveMode|juce::FileBrowserComponent::warnAboutOverwriting,[safe](const juce::FileChooser&fc){if(safe==nullptr)return;auto f=fc.getResult();if(f.getFileExtension().isEmpty())f=f.withFileExtension(".ucgvw");safe->status.setText(safe->processor.saveUserPreset(f)?"Preset guardado: "+f.getFileName():"No se pudo guardar",juce::dontSendNotification);});}
void UCGVoiceWonderEditor::loadPreset(){fileChooser=std::make_unique<juce::FileChooser>("Cargar preset",juce::File::getSpecialLocation(juce::File::userDocumentsDirectory),"*.ucgvw");auto safe=juce::Component::SafePointer<UCGVoiceWonderEditor>(this);fileChooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[safe](const juce::FileChooser&fc){if(safe==nullptr)return;auto f=fc.getResult();safe->status.setText(safe->processor.loadUserPreset(f)?"Preset cargado: "+f.getFileName():"Preset inválido",juce::dontSendNotification);});}
void UCGVoiceWonderEditor::timerCallback(){const float hz=processor.getDetectedPitchHz();if(hz>0){const float midi=StablePitchDetector::hzToMidi(hz);static const char*names[]={"C","C#","D","D#","E","F","F#","G","G#","A","A#","B"};int note=juce::jlimit(0,127,(int)std::round(midi));pitchReadout.setText(juce::String(names[note%12])+juce::String(note/12-1)+"  "+juce::String(hz,1)+" Hz",juce::dontSendNotification);}else pitchReadout.setText("NO PITCH",juce::dontSendNotification);}

